### PR TITLE
- not backward compatible. The init function now returns additional info received from the server such as the Server version - dependencies updates

### PR DESCRIPTION
**Pull request by florinpatrascu**

### CODE REVIEW

**Comment by florinpatrascu** [comment]
Hi Michael - I am implementing the bolt+routing protocol which requires a lot of changes from my side, including the ability to decide the type of connection used, based on the protocol. However, there are different methods used for obtaining the routing table from the server, and those are depending on the server info. Boltex is "hiding" that info, in the init, which is what I am trying to address with this PR. Please have a look, when you have time. Thank you - Florin

**Comment by mschae** [comment]
Hey Florin,

Super sorry for the late reply. I’m on paternity leave right now and
completely lost touch with the outside world. :)

I’ll merge this hopefully today and release a new version.

Sorry again,
Michael

-- 
*Michael Schaefermeyer*
michael.schaefermeyer@gmail.com
DE phone +49 (251) 590 8787 <//+49 (251) 590 8787>
US phone +1 (415) 439 0430 <//+1 (415) 439 0430>
about.me/mschae

**Comment by florinpatrascu** [comment]
Oh, no worries Michael!!! Take your time, and congratulations!!!! :)

**Comment by mschae** [comment]
Thanks again @florinpatrascu 0.4.0 was just released to hex. Sorry for the delay, the chaos normalizes here and I hope to get back to my laptop more regularly now.

**Comment by florinpatrascu** [comment]
Thank you, @mschae!!! Take care :)

**Pull request merged**
