### PR TITLE
Improved connection handling

### PR DESCRIPTION
**Pull request by mschae**

### CODE REVIEW

**Comment by florinpatrascu** [comment]
Hi @mschae - I see what breaks my stuff here :) You're returning now `[{:success, %{..} | {:success, %{...}]`, rather than a list of "successes": [{:success, %{..}, {:success, %{...}], as it used to be. On my side I am collecting every type of :success (a very important aspect!) with Keyword.get_values/2, which obviously does't apply anymore. Before looking into changing the way I use the :success values, what is your plan for this? Thank you!

**Comment by mschae** [comment]
God damn it. Sorry, I messed up wrapping that list. My intention was to keep returning a list and hopefully that's now what I do.

TFW you add tests but they are worthless 😞

**Comment by florinpatrascu** [comment]
Gooooooddddd Morning (well... GMT-5) :) Yes Sireeee, this is working niceeee! Ran the integration tests quickly, before getting late for work, and they are all green!! yay! Thank you, Michael! Let me know if this is the branch we want to support from now on, and I'll merge it to Bolt.Sips master and try to push it in the afternoon (tho' I have a bug reported by @vic, which I need to get to it before that - not related to this branch, I think?!). Once again, thanks man, this looks nice! 🍻

**Comment by florinpatrascu** [comment]
Hey @mschae - when you find a bit of time, please let me know if this branch can be merged to the master and I'll start integrating it in bolt_sips right away. Thank you!

**Comment by mschae** [comment]
Sorry for the delay, I'll get to it this weekend. Should also help with the issue you CCed me on regarding non-encodable entities.

**Comment by florinpatrascu** [comment]
Thank you so much for the quick reply, Michael. Indeed the suppport for the non-encodable entities is another advantage of this version :) I'll start integrating in a bit. Have a great day!

**Comment by florinpatrascu** [comment]
all green! 

🍻

**Comment by mschae** [comment]
@florinpatrascu v0.3.0 released (technically the run_statement change is backwards incompatible).

Feel free to merge and release, also please let me know if this fixes florinpatrascu/bolt_sips#17 (if not I will make sure to quickly add better messages).

**Pull request merged**
